In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("50_startups_dataset.csv")

In [3]:
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [5]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=dataset[['Profit']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=11)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
  'splitter':['best','random'],
  'max_depth':[1,2,3,4,5,6,7,8,10,11,12],
  'max_features':['auto', 'sqrt', 'log2']
             }
grid=GridSearchCV(estimator= DecisionTreeRegressor(),
                  param_grid=param_grid,
                  refit=True,
                  verbose=3,
                  n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 264 candidates, totalling 1320 fits

C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
440 fits failed out of a total of 1320.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
251 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
189 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [        nan         nan -0.11457308  0.03901165 -0.22104703  0.04686586
         nan         nan  0.09569986  0.27175131  0.40288521  0.29733486
         nan         nan  0.37430011 -0.67038346  0.32922821  0.18385444
         nan         nan  0.42656191  0.57093696  0.13888293  0.36431778
         nan         nan  0.3501173   0.53532622  0.2932696   0.53896733
         nan         nan  0.69635277  0.55905878  0.25307657  0.27754644
         nan         nan  0.68183398 -0.13412411  0.4525736   0.52437168
         nan         nan  0.60200114  0.10572655  0.56243007  0.37181138
         nan         nan -0.01432538 -0.32128845  0.67385214  0.30923438
         nan         nan  0.36954822  0.69387783  0.32104083  0.61262232
         nan         nan -0.08110133  0.36269732  0.04488546  0.53996388
         nan         nan  0.10220073  0.18107022  0.02477594 -0.2021298
         nan         nan -0.05285997 -0.29397915  0.62614328 -0.11751202
         nan         nan  0.17827113  0.35240179  0.33209305  0.62424536
         nan         nan  0.24469585 -0.13246202  0.35111846  0.60409856
         nan         nan  0.32260943  0.31804546  0.2283484   0.16610489
         nan         nan  0.40130858  0.31155451  0.71907833  0.54416917
         nan         nan  0.10931299  0.37386703  0.11635665 -0.3332747
         nan         nan  0.19726282  0.53069791  0.41918132  0.15849162
         nan         nan  0.63233993  0.39602214  0.38059189  0.19351172
         nan         nan  0.3908203   0.63171762  0.40440111  0.33432705
         nan         nan  0.61449391  0.19881058  0.36548465  0.19046639
         nan         nan -0.06176774  0.08207104  0.21262868 -0.47036239
         nan         nan -0.09569532  0.21736121 -0.03445927  0.30289748
         nan         nan  0.46285843 -0.27377509  0.14361925  0.13837017
         nan         nan  0.20413467  0.36882642  0.40003545 -0.75386061
         nan         nan  0.2762157   0.58059894  0.51046994  0.43776048
         nan         nan -0.00795694 -0.03205583  0.4658275   0.32886405
         nan         nan  0.43745415  0.71149923  0.61331543  0.25369746
         nan         nan  0.51811208  0.28900083  0.52780382 -0.28926259
         nan         nan  0.25067357  0.54829996  0.51078486 -0.5394795
         nan         nan -0.20151738  0.73933689  0.37476867  0.58132876
         nan         nan -0.34344941 -0.47476764  0.35777069  0.38649032
         nan         nan -0.51226808  0.40435421 -0.31509813 -0.3253024
         nan         nan  0.19306264  0.2307388   0.2568339   0.2573556
         nan         nan  0.444977    0.24857541  0.31827209  0.23014895
         nan         nan  0.36894838 -0.03485044  0.51761383  0.14162888
         nan         nan  0.6630452   0.07507023  0.17126818  0.35183309
         nan         nan  0.47437509  0.44999908  0.08631755  0.34876224
         nan         nan -0.10471551  0.46405628  0.61292672  0.50383247
         nan         nan  0.61710945  0.51670501  0.44301677  0.2926982
         nan         nan  0.64379732  0.18256509 -0.17326143  0.62801238
         nan         nan -0.05374859  0.46320203 -0.38182301  0.16516452
         nan         nan -0.50272539  0.48928192  0.14952086  0.50899904]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
regressor=grid.cv_results_
print("Best parameter{}:",format(grid.best_params_))

Best parameter{}: {'criterion': 'absolute_error', 'max_depth': 11, 'max_features': 'sqrt', 'splitter': 'random'}

In [9]:
table=pd.DataFrame.from_dict(regressor)

In [10]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012542,0.003776,0.000000,0.000000,squared_error,1,auto,best,"{'criterion': 'squared_error', 'max_depth': 1,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
1,0.003704,0.000852,0.000000,0.000000,squared_error,1,auto,random,"{'criterion': 'squared_error', 'max_depth': 1,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
2,0.033722,0.009639,0.016294,0.007848,squared_error,1,sqrt,best,"{'criterion': 'squared_error', 'max_depth': 1,...",0.225045,-0.005919,-0.046704,-0.132228,-0.613059,-0.114573,0.275881,153
3,0.036634,0.015457,0.028576,0.010712,squared_error,1,sqrt,random,"{'criterion': 'squared_error', 'max_depth': 1,...",0.009119,0.350335,-0.062632,0.511296,-0.613059,0.039012,0.388946,140
4,0.021073,0.006900,0.017741,0.013457,squared_error,1,log2,best,"{'criterion': 'squared_error', 'max_depth': 1,...",0.833163,0.518527,-0.362188,0.517665,-2.612402,-0.221047,1.260359,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,0.001630,0.001688,0.000000,0.000000,poisson,12,auto,random,"{'criterion': 'poisson', 'max_depth': 12, 'max...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,177
260,0.007856,0.001000,0.005173,0.001759,poisson,12,sqrt,best,"{'criterion': 'poisson', 'max_depth': 12, 'max...",0.549259,0.735540,0.848106,0.242276,-4.888809,-0.502725,2.202611,172
261,0.007410,0.001273,0.005042,0.000721,poisson,12,sqrt,random,"{'criterion': 'poisson', 'max_depth': 12, 'max...",0.532699,0.649632,0.698624,0.716086,-0.150631,0.489282,0.326297,42
262,0.006541,0.001437,0.007085,0.001659,poisson,12,log2,best,"{'criterion': 'poisson', 'max_depth': 12, 'max...",0.204358,0.887347,0.661176,0.451236,-1.456513,0.149521,0.834214,125
263,0.007565,0.001169,0.004741,0.001295,poisson,12,log2,random,"{'criterion': 'poisson', 'max_depth': 12, 'max...",0.555375,0.710680,0.081660,0.786871,0.410409,0.508999,0.249951,40