In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("50_startups_dataset.csv")

In [3]:
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [5]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=dataset[['Profit']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=11)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}

grid = GridSearchCV(
    estimator=RandomForestRegressor(),
    param_grid=param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)

grid.fit(x_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'max_depth': [None, 10, 20],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             verbose=3)

In [10]:
regressor=grid.cv_results_
print("Best parameter{}:",format(grid.best_params_))

Best parameter{}: {'bootstrap': True, 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}

In [11]:
table=pd.DataFrame.from_dict(regressor)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.981969,0.102680,0.058365,0.017876,True,None,1,2,100,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.970311,0.904405,0.963546,0.955558,0.850758,0.928916,0.045458,4
1,1.820797,0.110363,0.080736,0.024037,True,None,1,2,200,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.968800,0.901026,0.967211,0.960834,0.838271,0.927228,0.051100,6
2,0.884229,0.071059,0.047682,0.034396,True,None,1,5,100,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.967030,0.875244,0.967440,0.950222,0.816041,0.915195,0.060118,8
3,1.647930,0.137121,0.093306,0.028072,True,None,1,5,200,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.964214,0.869253,0.958418,0.960572,0.801505,0.910792,0.065222,15
4,0.931607,0.081992,0.077930,0.014088,True,None,2,2,100,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.961516,0.877076,0.957759,0.939458,0.848365,0.916835,0.045721,7
5,1.673124,0.066068,0.074222,0.008123,True,None,2,2,200,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.963269,0.877517,0.960019,0.943879,0.825302,0.913997,0.054104,9
6,0.850566,0.128636,0.039138,0.019932,True,None,2,5,100,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.948770,0.850526,0.958066,0.936630,0.799155,0.898629,0.062769,34
7,1.560334,0.111187,0.055033,0.024941,True,None,2,5,200,"{'bootstrap': True, 'max_depth': None, 'min_sa...",0.957310,0.855417,0.952199,0.936614,0.826262,0.905560,0.054074,23
8,0.679950,0.128060,0.065553,0.008773,True,10,1,2,100,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.973953,0.911529,0.962072,0.951523,0.858540,0.931523,0.042095,1
9,1.449615,0.076307,0.076004,0.007871,True,10,1,2,200,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.971078,0.902410,0.971565,0.959568,0.845208,0.929966,0.049478,2
10,0.780068,0.075838,0.041522,0.017316,True,10,1,5,100,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.958160,0.865452,0.963360,0.942776,0.798792,0.905708,0.064032,22
11,1.367282,0.126523,0.066875,0.026483,True,10,1,5,200,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.972160,0.868445,0.966675,0.953233,0.804264,0.912955,0.066043,12
12,0.734049,0.071612,0.047797,0.013773,True,10,2,2,100,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.956113,0.870358,0.952385,0.945604,0.824861,0.909864,0.052935,16
13,1.493969,0.140668,0.095344,0.013098,True,10,2,2,200,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.961522,0.878627,0.963206,0.940271,0.822562,0.913238,0.054734,11
14,0.710330,0.076064,0.045497,0.020655,True,10,2,5,100,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.957922,0.859094,0.936658,0.947394,0.820750,0.904364,0.054413,26
15,1.533003,0.125085,0.054886,0.019472,True,10,2,5,200,"{'bootstrap': True, 'max_depth': 10, 'min_samp...",0.948449,0.864624,0.952322,0.939855,0.814922,0.904034,0.054921,27
16,0.820918,0.076204,0.056940,0.022041,True,20,1,2,100,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.959975,0.908776,0.967262,0.956260,0.848028,0.928060,0.045006,5
17,1.716638,0.165810,0.071643,0.020239,True,20,1,2,200,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.967552,0.894550,0.970799,0.957160,0.859653,0.929943,0.044761,3
18,0.872410,0.105512,0.032608,0.026567,True,20,1,5,100,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.938247,0.867950,0.962771,0.941901,0.819316,0.906037,0.053877,19
19,1.644743,0.129396,0.071767,0.022981,True,20,1,5,200,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.956740,0.872270,0.965561,0.955592,0.817207,0.913474,0.058863,10
20,0.912601,0.106234,0.053634,0.017877,True,20,2,2,100,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.963564,0.878845,0.957201,0.928853,0.833129,0.912318,0.049609,13
21,1.855694,0.094497,0.079046,0.022156,True,20,2,2,200,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.960809,0.873762,0.958596,0.936387,0.826377,0.911186,0.052799,14
22,0.812965,0.098637,0.041319,0.029754,True,20,2,5,100,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.960531,0.862980,0.953846,0.936080,0.801194,0.902926,0.061572,29
23,1.595629,0.150101,0.066528,0.015662,True,20,2,5,200,"{'bootstrap': True, 'max_depth': 20, 'min_samp...",0.958837,0.866418,0.952623,0.938739,0.812411,0.905806,0.057206,21
24,0.641087,0.075360,0.056167,0.040668,False,None,1,2,100,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.929030,0.941988,0.847411,0.877148,0.900804,0.899276,0.034326,30
25,1.115519,0.116082,0.068612,0.012131,False,None,1,2,200,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.915136,0.944188,0.847464,0.876460,0.898827,0.896415,0.032963,36
26,0.543895,0.057224,0.049960,0.008699,False,None,1,5,100,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.764225,0.937037,0.843044,0.863762,0.871880,0.855989,0.055624,45
27,0.896765,0.039804,0.072096,0.015654,False,None,1,5,200,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.770666,0.937094,0.843062,0.865051,0.873000,0.857775,0.053630,43
28,0.505305,0.068935,0.043452,0.011899,False,None,2,2,100,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.893472,0.937618,0.948561,0.857126,0.886958,0.904747,0.033798,24
29,1.017928,0.069087,0.069546,0.016471,False,None,2,2,200,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.888025,0.937582,0.948732,0.852905,0.888345,0.903118,0.035315,28
30,0.485427,0.091725,0.044523,0.018064,False,None,2,5,100,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.773889,0.936833,0.943455,0.860962,0.876729,0.878373,0.061443,37
31,0.995522,0.076009,0.065805,0.007453,False,None,2,5,200,"{'bootstrap': False, 'max_depth': None, 'min_s...",0.761521,0.937006,0.944564,0.862746,0.875859,0.876339,0.065884,40
32,0.651589,0.111723,0.054980,0.021314,False,10,1,2,100,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.920446,0.945301,0.847460,0.876671,0.903873,0.898750,0.034006,32
33,1.115066,0.125982,0.082027,0.009451,False,10,1,2,200,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.927148,0.942792,0.847427,0.877589,0.901024,0.899196,0.034153,31
34,0.528880,0.019015,0.053541,0.015237,False,10,1,5,100,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.758037,0.936906,0.843270,0.864415,0.873220,0.855170,0.057738,48
35,1.069479,0.117752,0.094005,0.035024,False,10,1,5,200,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.768657,0.936794,0.843044,0.865051,0.872315,0.857172,0.054158,44
36,0.637012,0.037648,0.046241,0.015819,False,10,2,2,100,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.898150,0.937545,0.945949,0.859614,0.887856,0.905823,0.032042,20
37,1.134384,0.034330,0.070359,0.015506,False,10,2,2,200,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.898866,0.937653,0.948078,0.850175,0.887973,0.904549,0.035367,25
38,0.621103,0.076087,0.052588,0.025400,False,10,2,5,100,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.763678,0.936974,0.941699,0.863089,0.876396,0.876367,0.064524,39
39,0.935288,0.047972,0.059397,0.013190,False,10,2,5,200,"{'bootstrap': False, 'max_depth': 10, 'min_sam...",0.760820,0.936974,0.943082,0.862046,0.876396,0.875864,0.065847,42
40,0.544795,0.026587,0.026916,0.009775,False,20,1,2,100,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.926167,0.944085,0.847376,0.875979,0.899826,0.898687,0.034542,33
41,0.942011,0.121294,0.068387,0.011417,False,20,1,2,200,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.916623,0.944139,0.847373,0.877587,0.904298,0.898004,0.033151,35
42,0.469129,0.024286,0.052623,0.005854,False,20,1,5,100,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.762060,0.936906,0.843149,0.865051,0.871169,0.855667,0.056298,47
43,0.911682,0.085563,0.056722,0.014249,False,20,1,5,200,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.768458,0.936870,0.843270,0.858271,0.872665,0.855907,0.054127,46
44,0.464766,0.049941,0.044569,0.018313,False,20,2,2,100,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.907121,0.937749,0.948884,0.859021,0.888415,0.908238,0.032679,17
45,0.745866,0.064669,0.032220,0.007866,False,20,2,2,200,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.903982,0.937582,0.947497,0.857096,0.887856,0.906803,0.032988,18
46,0.448769,0.036384,0.032354,0.015917,False,20,2,5,100,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.759108,0.936974,0.943206,0.865051,0.876209,0.876110,0.066360,41
47,0.558754,0.055080,0.019403,0.001206,False,20,2,5,200,"{'bootstrap': False, 'max_depth': 20, 'min_sam...",0.764197,0.936870,0.943082,0.867129,0.875088,0.877273,0.064461,38