In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("50_startups_dataset.csv")

In [3]:
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [5]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=dataset[['Profit']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=11)

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
param_grid = {'alpha': [0.1, 1.0, 10.0, 100.0]}
grid=GridSearchCV(estimator=Ridge(),
                  param_grid=param_grid,
                  refit=True,
                  verbose=3,
                  n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(estimator=Ridge(), n_jobs=-1,
             param_grid={'alpha': [0.1, 1.0, 10.0, 100.0]}, verbose=3)

In [14]:
regressor=grid.cv_results_
print("Best parameter{}:",format(grid.best_params_))

Best parameter{}: {'alpha': 100.0}

In [15]:
table=pd.DataFrame.from_dict(regressor)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.025318,0.012483,0.012814,0.005601,0.1,{'alpha': 0.1},0.866968,0.916558,0.972252,0.954294,0.800255,0.902065,0.062388,4
1,0.020633,0.003608,0.009522,0.004697,1.0,{'alpha': 1.0},0.873495,0.917069,0.973213,0.954470,0.801030,0.903855,0.061712,3
2,0.033480,0.014431,0.014553,0.008267,10.0,{'alpha': 10.0},0.895979,0.918454,0.975558,0.954734,0.805158,0.909977,0.059260,2
3,0.017104,0.006653,0.008636,0.005425,100.0,{'alpha': 100.0},0.910520,0.919193,0.976554,0.954628,0.809124,0.914004,0.057622,1